# Exercise 1 DS-GA 1012

# Preface

This first exercise/homework is primarily meant to ensure that you have access to a machine with the software that you'll need for this course. Complete the assignment by filling in code where necessary using Jupyter!

## What NumPy and PyTorch are and do

Both NumPy and PyTorch are python packages that allow for complex scientific computing with NumPy array and Tensor objects. These objects allow the easy definition of vectorized and matrix-level operations. Researchers and programmers can use these tools to quickly prototype models which involve lots of matrix calculations such as deep neural networks. As you can imagine, these packages allow complex manipulations and will allow you to define things like computation graphs. 

'Tensors' and 'NumPy Arrays' are used as general terms to refer to an n-dimensional tensor or vector and have the same sorts of operations and properties. If some of the terms in the previous section aren't clear or don't make sense, that's okay and you will get a good handle of these as you work through the course!

# Making sure everything works

Before you can go any farther, you'll need to make sure you have NumPy and PyTorch installed. For some help with that, see here [INSERT LINK]

Once the packages are installed, run the following commands,

In [2]:
import numpy as np

If that worked as expected, you should be able to run the below a few times and get different outcomes each time.

In [3]:
np.random.rand()

0.9629027288723141

In [4]:
np.random.rand()

0.7785238870663048

Now let's try importing and testing PyTorch.

In [5]:
import torch

First we define some tensor variables.

In [6]:
x = torch.rand(10,5)
w = torch.rand(2,10)

y = torch

Then we check their sizes:

In [7]:
print(x.size())
print(w.size())

torch.Size([10, 5])
torch.Size([2, 10])


Then lets multiply these tensors and store in a variable y:

In [8]:
y = torch.matmul(w,x)
print(y)

tensor([[2.8027, 2.6294, 2.1551, 2.7879, 1.8008],
        [2.4267, 2.1846, 2.6856, 2.8341, 2.3629]])


You can operate on tensors easily!

In [9]:
z = torch.rand(10,5)
print(x + z)
print(torch.add(x,z))

tensor([[1.4291, 0.7176, 1.3768, 0.5538, 0.9239],
        [1.0210, 0.4996, 1.0168, 0.8318, 0.2670],
        [1.4106, 1.0108, 1.2782, 0.6946, 1.2041],
        [1.0502, 0.6441, 0.8556, 1.6262, 0.6231],
        [0.9296, 0.8330, 0.5869, 1.1510, 1.4083],
        [0.6372, 0.8850, 1.2736, 0.5684, 0.9985],
        [0.5810, 1.1300, 1.3204, 1.3103, 0.8114],
        [1.3085, 1.2818, 0.8390, 1.2725, 0.7058],
        [1.1220, 1.2282, 0.6200, 1.3005, 0.9295],
        [0.6178, 0.3816, 1.4920, 1.0970, 1.4167]])
tensor([[1.4291, 0.7176, 1.3768, 0.5538, 0.9239],
        [1.0210, 0.4996, 1.0168, 0.8318, 0.2670],
        [1.4106, 1.0108, 1.2782, 0.6946, 1.2041],
        [1.0502, 0.6441, 0.8556, 1.6262, 0.6231],
        [0.9296, 0.8330, 0.5869, 1.1510, 1.4083],
        [0.6372, 0.8850, 1.2736, 0.5684, 0.9985],
        [0.5810, 1.1300, 1.3204, 1.3103, 0.8114],
        [1.3085, 1.2818, 0.8390, 1.2725, 0.7058],
        [1.1220, 1.2282, 0.6200, 1.3005, 0.9295],
        [0.6178, 0.3816, 1.4920, 1.0970, 1.4167]]

Unlike TensorFlow computation is done in place and not in a session, so you can see the tensor computation as you go. This makes debugging and general model building much easier!

## In-class exercise  
(taken from Sam's F16 3340.002 Exercise 1)

### Part 1:

Write a python function using NumPy to compute the following function of `x`. You can set $\mu$ to 0 and $\sigma$ to 1. This happens to be the probability density function for a normal distribution, but we're just using it as an arbitrary demo, and you shouldn't use any preexisting code for this particular distribution. You'll likely need to search for relevant NumPy documentation.

$$ \frac{1}{2\sigma^2\pi} e^{-\frac{(x-\mu)^2}{2\sigma^2}} $$

In [10]:
def np_fn(x):
    """
    x is input vector
    """
    # Replace with your code.
    pass 

Assume `x` is a vector. You should be able to run the following command and get the subsequent result:

In [11]:
x = np.array([0, 1, 2, 3])
np_fn(x)

Expected output: `array([ [0.15915494 0.09653235 0.02153928 0.00176805]])
`

### Part 2:
Now try to write the same function (`pytorch_fn(x)`) in PyTorch.

In [12]:
def pytorch_fn(x):
    """
    x is an input float tensor
    """
    # Replace with your code.
    pass

You should be able to run command below, and get the same output as above. This is quite straight forward and may (probably should) look very similar to np_fn!

In [13]:
x = torch.FloatTensor([0,1,2,3])
pytorch_fn(x)

Credits: Much of this was taken from Sam Bowman's TensorFlow Ex1 for F16 3340.002.

### Part 3:

Do a linear regression using numpy! Import whatever packages you see fit.

In [4]:
x = np.random.random(10)
y = np.random.random(10)

# Your code! #

In [3]:
print("r-squared:", r_value**2)

r-squared: 0.009421204405005334
